### ISSUE TITLE
LOGO显示不正常

### ISSUE THREAD

**Issue by Vincent-X** [logeast/dumi-theme-vite#1]
Attempted import error: 'LOGO_320_BASE64' is not exported from 'dumi/theme/slots/DefaultLogo' (imported as 'LOGO_320_BASE64').

**Comment by orienslu** [comment]
感谢反馈，我将会在下一个版本修复这个问题，到时候周知你。

**Comment by orienslu** [comment]
@Vincent-X  [0.0.16](https://www.npmjs.com/package/dumi-theme-vite) 版本已经修复了，请使用该版本。

同时欢迎继续反馈问题。
